---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-authz-http-basic-auth-openapi-path-with-auth
  name: ext-authz-http-basic-auth-openapi-path-with-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-http-basic-auth-openapi-path-with-auth
  template:
    metadata:
      labels:
        app: ext-authz-http-basic-auth-openapi-path-with-auth
    spec:
      containers:
        - image: docker.io/kubeshop/ext-authz-http-basic-auth
          name: ext-authz-http-basic-auth
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-authz-http-basic-auth-openapi-path-with-auth
  name: ext-authz-http-basic-auth-openapi-path-with-auth
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ext-authz-http-basic-auth-openapi-path-with-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: httpbin
